### ISSUE TITLE
langium-config-schema.json is missing in ./data folder of installed langium-vscode extension

### ISSUE THREAD

**Issue by hpopov** [langium/langium#1006]
No langium config JSON schema detected by VSCode when editing `langium-config.json` for langium-based LS. 
![VSCode warning](https://user-images.githubusercontent.com/41228916/228532550-8ff5220b-025d-48b3-8f08-bbeea14aebe2.png)
![Missing file in extension installation directory](https://user-images.githubusercontent.com/41228916/228534893-14911873-24ff-4259-9403-cefbbf692916.png)
  
According to #218, the JSON schema support was added to langium-vscode extension. In #240 it was done by copying schema JSON from `langium-cli` to `langium-vscode` package in prepare script. However, this file is absent in VSCode extension folder, when installed from the VSCode Marketplace.  

Perhaps the extension needs to be republished?

Langium version: 1.1.0
Package name: langium-vscode
OS: Windows 11
I use regular, Microsoft-bundled VSCode (`code`)

## Steps To Reproduce

1. Install `langium.langium-vscode` extension in VSCode (locally),
2. Go to `~/.vscode/extensions/langium.langium-vscode-1.1.0/data` and see no `langium-config-schema.json` file there.

Link to code example: since the problem is in **VSCode extension installation**, it shouldn't matter, which Langium-based project to open. However, if it may help, I was working over [tasklist-lang](https://github.com/Crystal-VPL/tasklist-lang).

## The current behavior

After installing langium-vscode extension, `langium-config.json` is not validated, and no autocomplete suggested by VSCode.

## The expected behavior

After installing langium-vscode extension, there are syntax validation and hints for `langium-config.json`.

**Comment by msujew** [comment]
@hpopov Thanks for the report, a fix (#1007) will be released in a few days with version 1.2.0 of Langium.
