### ISSUE TITLE
JSDoc hover disapper after upgrading langium from 1.0.1 

### ISSUE THREAD

**Issue by jiashengguo** [langium/langium#1052]
Langium version:1.2.0
Package name: langium

## Steps To Reproduce

![image](https://github.com/langium/langium/assets/16688722/e21d8fe6-c5f2-4e81-aa32-1e28035e07a6)

It used to have the JsDoc hover hint by default when using langium 1.0.1.  After upgrading to 1.1.0, it's gone.   It is still not there even after upgrading to 1.2.0.  

Is there any place we need to manually turn on it now?

**Comment by msujew** [comment]
I cannot reproduce this issue on `1.2.0`:

![image](https://github.com/langium/langium/assets/4377073/1d445f8b-cbd5-4149-9dc3-f2ec28a3eb38)

Can you give some better reproduction steps for this issue?

**Comment by jiashengguo** [comment]
@msujew,  after taking a deep look, I found that JSdoc comments require two stars in the beginning line, whereas in our code we only use one star, which I don't know why it was working in langium 1.0.1. 

Anyway, thanks for the efforts on it, and sorry for the trouble, I will update our code instead.

**Comment by msujew** [comment]
Right, the old version didn't follow JSDoc at all. It basically just stripped the `/*`, `*` and `*/` symbols and displayed everything in between in the hover. The new JSDoc parser actually follows the spec and therefore requires `/**` at the start. You can change that if you like though. You just need to override the [`DocumentationProvider`](https://github.com/langium/langium/blob/main/packages/langium/src/documentation/documentation-provider.ts).
