### ISSUE TITLE
Refactor syntax error provider into service

### ISSUE THREAD

**Issue by msujew** [langium/langium#1058]
The current [syntax error message provider](https://github.com/langium/langium/blob/915ff5d53daf76415b0a838540c90e3437d3f8d0/packages/langium/src/parser/langium-parser.ts#L353-L396) is hardcoded and cannot be modified. It would be nice to refactor that class into a service that can be overriden by devs to better fit their needs.

**Comment by spoenemann** [comment]
Let's schedule this for 2.0 as a potentially breaking change.
