### ISSUE TITLE
Perhaps parser rules should be treated as fragments when used as fragments.

### ISSUE THREAD

**Issue by trusktr** [langium/langium#1089]
For example, suppose I have this:

```js
ArrowFunctionExpression:
	Parameters (":" ReturnType)? "=>" body=(ArrowReturnExpression | Block);
```

If I try to do this, the parser will incorrectly detect an async arrow function (`() => {}`) to be an arrow function:

```js
ArrowFunctionExpression:
	Parameters (":" ReturnType)? "=>" body=(ArrowReturnExpression | Block);

AsyncArrowFunctionExpression:
	"async" ArrowFunctionExpression;
```

To get around the issue, I can duplicate the code:

```js
ArrowFunctionExpression:
	Parameters (":" ReturnType)? "=>" body=(ArrowReturnExpression | Block);

AsyncArrowFunctionExpression:
	"async" Parameters (":" ReturnType)? "=>" body=(ArrowReturnExpression | Block);
```

or I can split the shared code to an actual fragment:

```js
fragment ArrowFrag:
	Parameters (":" ReturnType)? "=>" body=(ArrowReturnExpression | Block);

ArrowFunctionExpression:
	ArrowFrag;

AsyncArrowFunctionExpression:
	"async" ArrowFrag;
```

It seems intuitive and natural to want to use a parser rule in the same manner as a fragment. I'm not sure if there are any reasons why not to do it.

For now making a fragment is the path I go and is simple enough, but I wanted to share the feeling my intuition had.

**Comment by msujew** [comment]
I don't really see this as a useful feature, or rather: It invites more trouble than it is worth. Unassigned subrule calls have clear semantics depending on the target rule: Parse and return the resulting object in case of a normal rule, or inline for fragment rules. Muddling these two together is arguably not a good idea.

Note that in your case I would recommend to just add a flag `isAsync?='async'` to the arrow function rule. I don't see a lot of benefit to intrpduce a separate rule/type for that.

**Comment by msujew** [comment]
I'll close this for now. I think both usages of unassigned subrules have their clearly defined use cases as outlined in our documentation. See [here](https://langium.org/docs/grammar-language/#unassigned-rule-calls) and [here](https://langium.org/docs/grammar-language/#rule-fragments).
