### ISSUE TITLE
Reference does not resolve...

### ISSUE THREAD

**Issue by Reyems** [langium/langium#1102]
Langium version: Latest

## Steps To Reproduce
1. In playground using the following Grammar description: 
grammar WPSLang

hidden terminal WS: /\s+/;
terminal ASSIGN : /\=/;
terminal NUMBER returns number: /-?(0|[1-9]\d*)(\.\d+)?([eE][+-]?\d+)?/;
terminal IDEN : /\w+/;

LitVAL: value=(NUMBER);
AnyVAR: ref=[VarDEF:IDEN];
AnyVAL: LitVAL | AnyVAR;

VarDEF: name=IDEN ASSIGN value=(AnyVAL);

DLINE: defn=VarDEF;

entry WPS:
  (  LINES+= DLINE )*;

2. For Content test with :
 Var1234=1234
 NewVar=Var1234

## The current behavior
Reference to Var1234 does not resolve. If DLINE is changed to: "DLINE: VarDEF" it resolves normally

**Comment by msujew** [comment]
Working as designed: We use lexical scoping as a default mechanism. Since you define your element in a new block (i.e. `DLINE`), it is only available within that block. Take a look at our [scoping guides](https://langium.org/guides/scoping/) to see how to implement what you're trying to do.

**Comment by Reyems** [comment]
Thanks
