### ISSUE TITLE
Improve the API of CompositeGeneratorNode

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#122]
The generator node API should be improved to make appending and indenting generated code easier.

We currently use it heavily in `langium-cli`. The goal of this task is to make the generator code more compact and readable.

**Comment by msujew** [comment]
Maybe something like `CompositeGeneratorNode.indent(params)` that returns a `IndentNode` constructed with the specified `params`. This node will also automatically be appended to the `CompositeGeneratorNode`. This would remove boilerplate code such as:

```ts
const indent = new IndentNode();
...
composite.children.push(indent);
```

And reduce it to a call like

```ts
const indent = composite.indent();
```

WDYT?

**Comment by spoenemann** [comment]
Yes, and it could also accept a callback as optional parameter:

```
composite.indent(indentNode => {
    ...
});
```

The nice thing about this: the generator code is indented as well.

**Comment by spoenemann** [comment]
In addition I'd propose a method `append` as replacement for `children.push`. Potential signature:

```typescript
append(...args: Array<GeneratorNode | string | (CompositeGeneratorNode) => void>): CompositeGeneratorNode   // returns `this`
```

**Comment by spoenemann** [comment]
I also feel that including both `string` and `TextNode` in the definition of `GeneratorNode` is redundant. I would either drop `TextNode` or automatically convert strings to `TextNode` in the `append` method.

**Comment by spoenemann** [comment]
Last remark for now: I propose making the properties of the GeneratorNode classes public and dropping the getters and setters.
