### ISSUE TITLE
Enable regular expression flags for terminal rules

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#127]
See https://github.com/TypeFox/langium/pull/126#discussion_r657646003.  JavaScript supports [flags](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags) to control the behavior of regular expressions. Shall we enable in the grammar language?

**Comment by dhuebner** [comment]
I don't know how useful are other flags, but those seen to be useful: 

s | Allows . to match newline characters.
-- | --
i | Case-insensitive search.

Will mean to change the RegexLiteral to:
`\/(?![*+?])(?:[^\r\n\[/\\]|\\.|\[(?:[^\r\n\]\\]|\\.)*\])+\/[a-z]?`

`[a-z]?` is if regex will become more options in the future.

**Comment by spoenemann** [comment]
This idea does not work well with the changes made in #288. Let's postpone it for now.

**Comment by msujew** [comment]
Regarding case sensitivity, there's also a [group flag](https://stackoverflow.com/a/34585559) which allows to make search case insensitive. I would argue, that users which are interested in this feature should use the group flag instead of the global regex flag.

**Comment by dhuebner** [comment]
What about a new keyword for multiline matching?

**Comment by msujew** [comment]
@dhuebner Multiline matching is always enabled, no flag necessary :)

**Comment by dhuebner** [comment]
@msujew 
I meant the `s` flag for: Allows . to match newline characters.

**Comment by dhuebner** [comment]
Keyword is not a good idea, because this flag regex specific

**Comment by Josh-Cena** [comment]
Hi, just want to mention that the `u` flag is quite useful. For example, all JS identifiers use the syntax `/[$_\p{ID_Start}][$\u200c\u200d\p{ID_Continue}]*/u`, but at the moment there's no easy way to specify Unicode character classes.

**Comment by msujew** [comment]
For now, the unicode flag isn't supported in Chevrotain. It is part of a larger lexer issue, see https://github.com/Chevrotain/chevrotain/issues/1670.

Note that custom `pattern` functions can still be used to achieve the same effect, so it's still possible to achieve this functionality in Langium.
