### ISSUE TITLE
Grammar without references generates invalid `ast.js`.

### ISSUE THREAD

**Issue by dslmeinte** [langium/langium#130]
Langium version: 0.1.0
Package name: ?

## Steps To Reproduce

1. Make a grammar without references (`...=[Person|ID]`).
2. Run `langium:generate`.

## The current behavior

`src/generated/ast.ts` has a syntax error at `export type <language name>AstReference = ;`

## The expected behavior

I guess `never` would work as RHS value if there are no references.

**Comment by msujew** [comment]
Thanks for your issue @dslmeinte. I think `never` is an appropriate type as well, especially since the generated `getReferenceType` method will always throw on any input.
