### ISSUE TITLE
Wrong range of subexpression in arithmetics example

### ISSUE THREAD

**Issue by Pluralia** [langium/langium#145]
Subexpressions can lose their `$cstNode` field, and it's impossible to determine their range in a document.

Langium version: 0.1.0
Package name: langium

## Steps To Reproduce

1. Open VSCode with `arithmetics` extension
2. Open [example/example1.calc](https://github.com/langium/langium/blob/plu/arithmetics-validation/examples/arithmetics/example/example1.calc) file
3. `1 + 3` in [3rd line](https://github.com/langium/langium/blob/plu/arithmetics-validation/examples/arithmetics/example/example1.calc#L3) has to be highlighted [because of a validation error], however, a `module` keyword is highlighted

## The current behavior
`module` keyword is highlighted instead of the subexpression

## The expected behavior
The subexpression is highlighted

**Comment by msujew** [comment]
Right now, left recursive expressions are missing their `$cstNode` properties, since they skip the whole `LangiumParser.construct` call. I'll work on that.
