### ISSUE TITLE
Provide Language id and file extension information

### ISSUE THREAD

**Issue by dhuebner** [langium/langium#168]
I need a service where I can get the language id and the file extension.
Language id can be fetched from the document, but I do not have one when indexing

**Comment by danieldietrich** [comment]
It would be nice to have a metadata service for the language. It is better to have a central place for such information that collecting it from n arbitrary locations.

(Maybe we can also include the Langium version there?)

**Comment by dhuebner** [comment]
Do you have a good name for such a property holder?

**Comment by msujew** [comment]
My proposal:

```ts
export interface LanguageMetaData {
    languageId: string;
    extensions: string[];
}
```

**Comment by dhuebner** [comment]
You like `meta` in name too, than it seem to be the right wording

**Comment by spoenemann** [comment]
See my comment in the PR, I'd prefer `fileExtensions` for clarity.

**Comment by dhuebner** [comment]
It seem to be more clear, especially for new users. We should add documentation comments as well
