### ISSUE TITLE
Change the syntax for hidden terminals

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#185]
I propose to change

```
grammar Foo
hidden(WS, SL_COMMENT, ML_COMMENT)

terminal WS: /\s+/;
terminal ML_COMMENT: /\/\*[\s\S]*?\*\//;
terminal SL_COMMENT: /\/\/[^\n\r]*/;
```

to

```
grammar Foo

hidden terminal WS: /\s+/;
hidden terminal ML_COMMENT: /\/\*[\s\S]*?\*\//;
hidden terminal SL_COMMENT: /\/\/[^\n\r]*/;
```

The only potential drawback I can think of is that it becomes less clear which terminals shall be hidden in a scenario where you have multiple languages in one project. So let's keep this open until we have a clear path for handling multiple languages and reusability of grammar rules.

**Comment by msujew** [comment]
I am heavily in favor of this one. It always irked me, that hidden tokens where defined on the grammar/rule level. I actually think that we can't even support hidden tokens on a rule level, since that is not possible in Chevrotain.

**Comment by spoenemann** [comment]
Note: We should still allow the old syntax, but mark it with a validation error. This way we can offer a code action to fix it.
