### ISSUE TITLE
Extend terminal syntax to enable composition

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#194]
In Xtext you can use other terminal rules in a terminal definition. Shall we add this composition to our terminals as well?

The alternative is to use datatype rules, which already support composing terminals. The difference is that a terminal produces a single token, while a datatype rule can produce many tokens in the CST.

**Comment by msujew** [comment]
I explicitely disabled this feature, to improve adoption in the JS ecosystem (which heavily uses Regex). We could theoretically support both use cases. We would have to transform a terminal based on other terminals into a single regex during the parser initialization.

**Comment by spoenemann** [comment]
Yes, I imagine supporting the base operators `|`, `?`, `+`, `*` with regexps, terminals or keywords:
```
terminal TERM1: 'foo'? (TERM2 | /[a-z]+/)*;
```
This should be fairly easy to transform to an expanded regexp.
