### ISSUE TITLE
Review and fix find references/index using domainmodel example

### ISSUE THREAD

**Issue by dhuebner** [langium/langium#214]
## Steps To Reproduce
Find references does not work properly. Example: change line 5 in blog.dmodel to many posts: E1, then "Find All Reference" shows one hit from blog.dmodel and one from qualified-names.dmodel when started from the new reference, while it shows two hits from qualified-names.dmodel when started from the declaration.

**Comment by dhuebner** [comment]
@spoenemann 
The problem here is that I explicitly exclude `local` cross references from the index, see:
https://github.com/langium/langium/blob/6dd874b70d0debb08c52cad73cd8e142ca40873b/packages/langium/src/index/ast-descriptions.ts#L92-L94

These cross references are not interesting for a global index lookup (e.g. isAffected), so I'm not sure how to proceed here.
One option is to create all the reference descriptions for a document but mark them with `local = true` so we can skip them when doing a lookup for foreign cross references.

**Comment by spoenemann** [comment]
But shouldn't the call to `findLocalReferences` ensure that the references that are local to the declaration are included as well?
