### ISSUE TITLE
Automatically detect comment rules in grammar

### ISSUE THREAD

**Issue by msujew** [langium/langium#228]
For #204, we need some way to detect comment rules in grammars. I propose the following solution:

Every terminal that is hidden but does not match a white space string is a comment terminal by default.

**Comment by dhuebner** [comment]
This is a bit vague IMO. Is it not possible to compare the terminal rule name with default comment rule names ML_COMMENT and SL_COMMENT?

**Comment by msujew** [comment]
It's a bit more complicated than that. E.g. users could decide to rename these terminals or simply add a third kind of comment.

This is never a problem during runtime, because we have a `GrammarConfig` that contains all comment terminal names. However, when generating the textmate grammar, we don't know about this. Therefore, we have to identify all comment terminals while the `langium-cli` is running.

**Comment by dhuebner** [comment]
> when generating the textmate grammar, we don't know about this

It must be somehow possible to get the information from GrammarConfig, or maybe the information about "What is a comment" should be placed somewhere else?
