### ISSUE TITLE
Domainmodel example: refactor qualified name provider

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#236]
The current implementation of the domainmodel example extends the `NameProvider` with an additional method to handle qualified names, which leads to type casting of the service in other classes (see https://github.com/langium/langium/pull/229#discussion_r712983533). A simple solution would be to move that method to a new custom service `QualifiedNameProvider`. But we should consider whether generalizing this case makes sense. Xtext does this with a `QualifiedName` type; I'm not sure whether we want to go down that path.

**Comment by dhuebner** [comment]
I personally don't like how extending the default API works at the moment.
There is no way to use the additional API inside a custom service implementation except of casting things. Adding a new service interface is an alternative, but imagine a case where an additional function belongs to one special service and is used in only one other service. Creating a new service in that case is a bit to much overhead.
I would love to see a simpler way to achieve what is requested in this issue description.

**Comment by spoenemann** [comment]
Our current DI solution is more restrictive than Guice / Inversify, but it's also type-safe, which is great.

> Creating a new service in that case is a bit too much overhead.

It's not that much: one line for declaring the new service and one line for assigning the constructor call to it.

**Comment by dhuebner** [comment]
> but it's also type-safe, which is great.

I don't propose to change `nameProvider` field to Object. I'm rather looking for a more extensible alternative on how our default implementations are implemented.

**Comment by dhuebner** [comment]
Maybe something like this?


Default service implementation:
```ts
export class DefaultScopeComputation<ST extends LangiumServices> implements ScopeComputation {
    protected readonly services: ST;

    constructor(services: ST) {
        this.services = services;
    }

    protected nameProvider(): NameProvider {
        return this.services.references.NameProvider;
    }

    protected descriptions(): AstNodeDescriptionProvider {
        return this.services.index.AstNodeDescriptionProvider;
    }
}
```

User implementation:
```ts
export class DomainModelScopeComputation extends DefaultScopeComputation<DomainModelServices> {
    protected nameProvider(): DomainModelNameProvider {
        return this.services.references.NameProvider;
    }
    // can use DomainModelNameProvider with this.nameProvider().getQualifiedName()
}
```

Domain Module:
```ts
export type DomainModelAddedServices = {
    validation: {
        DomainModelValidator: DomainModelValidator
    },
    references: {
        NameProvider:  DomainModelNameProvider
    }
}
```
