### ISSUE TITLE
Implement change affection computation

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#237]
https://github.com/langium/langium/blob/83986e9e91f116a57e8263efb4941d2215eca45b/packages/langium/src/documents/document-builder.ts#L105-L107

This placeholder implementation should be replaced with an index lookup to avoid rebuilding the whole workspace on every change.

**Comment by dhuebner** [comment]
I think it depends on #210

**Comment by dhuebner** [comment]
Implementation is in my branch https://github.com/langium/langium/tree/dh-isAffected-237
It depends  #231 but can be rebased on top of master with a small change to `isLocal` computation:

https://github.com/langium/langium/blob/489f39cc460877f02c58cd07655ee535bababda4/packages/langium/src/documents/document-builder.ts#L108-L113

Feel free to open a PR for `dh-isAffected-237` or just copy paste what you need
