### ISSUE TITLE
Add dummy rules highlighting

### ISSUE THREAD

**Issue by pluralia** [langium/langium#265]
Rules, unreachable from the entry rule, called dummy rules. Currently they are useful and used to generate AST types, however, we are going to replace them for that use case by extending the grammar language with special type rules ([discussion/91](https://github.com/langium/langium/discussions/91)). This makes dummy rules useless, so we should highlight them for fast and simple detection and further embedding or removing.

**Comment by msujew** [comment]
Dummy rules are already marked as `unused` as of https://github.com/langium/langium/commit/ad265815d5f6a4df27dad7b708a528f8aad5af29:

![image](https://user-images.githubusercontent.com/4377073/138122277-e36353e6-eb65-4680-b572-097014b8ff5e.png)
