### ISSUE TITLE
Domainmodel example: Renaming with qualified name does not work

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#277]
Langium version: #275
Package name: langium

## Steps To Reproduce

1. Open `datatypes.dmodel`
2. Select `Date`
3. Press F2
4. Enter a new name

## The current behavior

The datatype name is changed in `blog.dmodel`, but it loses the `complex.` prefix.

## The expected behavior

The new name should include the package name.

**Comment by dhuebner** [comment]
@spoenemann 
Should supporting renaming of a package e.g. `complex` also be a part of this issue?

**Comment by dhuebner** [comment]
What is also strange, you can exec `Rename Symbol` for every QName CSTNode part, which doesn't make much sense:
<img width="375" alt="Bildschirmfoto 2022-03-02 um 15 28 53" src="https://user-images.githubusercontent.com/454322/156381467-b89795e4-45f0-40aa-b18d-14c304e5f436.png">
<img width="370" alt="Bildschirmfoto 2022-03-02 um 15 28 23" src="https://user-images.githubusercontent.com/454322/156381477-74bc9159-fac5-4170-8d8e-54eab10112c1.png">
<img width="366" alt="Bildschirmfoto 2022-03-02 um 15 28 12" src="https://user-images.githubusercontent.com/454322/156381483-6949e14d-3477-40fb-968a-2af682e8e0cf.png">

Every such a rename request will end up in rename service with a selected QName part (`comlex` or `.` or `Date`) as `newText`

**Comment by spoenemann** [comment]
> Should supporting renaming of a package e.g. complex also be a part of this issue?

Ideally yes (needs special handling to rename all references to contained classes).

> What is also strange, you can exec Rename Symbol for every QName CSTNode part, which doesn't make much sense

That seems to be a client side behavior. Don't know what we can do to fix it.

**Comment by insafuhrmann** [comment]
The issue seems to be no longer present. I cannot reproduce with current main state.

**Comment by spoenemann** [comment]
?? I can still reproduce following the steps described at the top.

**Comment by insafuhrmann** [comment]
Yes, today I also can (with todays state of main). Not clear why it worked yesterday for me on the main branch. However, I'll update the fix.
