### ISSUE TITLE
Refactor `IndexManager.skip` into service

### ISSUE THREAD

**Issue by msujew** [langium/langium#280]
Instead of overriding the `skip` method, we should write an `WorkspaceIgnoreService` that checks whether a folder/file should be included in the workspace. One possible default implementation checks the `.gitignore` file and excludes folders/files based on that.

**Comment by spoenemann** [comment]
More generally, that service could be queried to provide all URIs of language documents in the workspace. It's important that we can customize the base path, for example search only inside the `src` subfolder.
