### ISSUE TITLE
Wrong links in CHANGELOG of langium project

### ISSUE THREAD

**Issue by hallvard** [langium/langium#287]
Langium version: 0.2.0
Package name: languid

## Steps To Reproduce

1. Navigate to https://github.com/langium/langium/blob/main/CHANGELOG.md
2. Check the links to the module-specific CHANGLOG.md files, the latter two point to the one for the first module

Link to code example:

## The current behavior

Two links are incorrect

## The expected behavior

All links are correct

**Comment by spoenemann** [comment]
Thanks @hallvard!
