### ISSUE TITLE
Name clashing of terminal and non-terminal rules

### ISSUE THREAD

**Issue by Pluralia** [langium/langium#294]
Langium version: 0.2.1

## Steps To Reproduce

Generate an AST by a grammar that contains the same word as a keyword and a rule name. For example, here the word `Function` gives name clashing.

```
Function:
	GlobalFunction | LocalizedText | Validator | ParameterList;

FunctionTypeReference:
	'Function' ParameterList ('to' returnType=TypeReference)?;
```

## The current behavior

Rises an error: `The grammar has both a Terminal(Token) and a Non-Terminal(Rule) named: <Function>.`

## The expected behavior

No errors. As a possible solution, support `^` like it's made for the keywords and property names clashing, so we have a keyword `'Function'` and a `^Function` rule.

**Comment by Pluralia** [comment]
Due to [#372](https://github.com/langium/langium/pull/372#discussion_r786616304) another solution has to be presented.

**Comment by spoenemann** [comment]
I propose to rename keyword tokens instead of grammar rules. I think that will be easier to understand for users.

Example: for a `'Function'` keyword, name the token `KW:Function`.
