### ISSUE TITLE
Incorrect AST generation with actions

### ISSUE THREAD

**Issue by Pluralia** [langium/langium#297]
An AST, generated from the grammar bellow, doesn't contain an interface `StaticAccessExpression`. Also, interfaces `StaticSymbolReference` and `StaticMemberAccess` are generated incorrectly.

```
Model:
	elements+=Element*;

Element:
	StaticAccessExpression;

StaticAccessExpression:
	{StaticSymbolReference} ref=ID
	({StaticMemberAccess.receiver=current} '.' member=ID)*;

StaticSymbolReference:
	{StaticSymbolReference} ref=ID;

StaticMemberAccess:
	{StaticMemberAccess} '.' member=ID;

terminal ID: /\$?[_a-zA-Z][\w_]*/;
```

Langium version: 0.2.1

## Steps To Reproduce

1. Generate an AST with the grammar above
2. Check out the `StaticAccessExpression`, `StaticSymbolReference` and `StaticMemberAccess` interfaces in the AST

## The current behavior

The generated AST doesn't contain the `StaticAccessExpression` interface. `StaticSymbolReference` and `StaticMemberAccess` interfaces don't extend `StaticAccessExpression`.

```
export interface StaticSymbolReference extends AstNode {
    member: string
    receiver: StaticAccessExpression
    ref: string
}

export interface StaticMemberAccess extends StaticSymbolReference {}

```

## The expected behavior

A correctly generated AST:

```
export interface StaticAccessExpression extends Element {}

export interface StaticSymbolReference extends StaticAccessExpression {
    ref: string
}

export interface StaticMemberAccess extends StaticAccessExpression {
    member: string
    receiver: StaticAccessExpression
}
```

**Comment by jbicker** [comment]
Closed :-)
