### ISSUE TITLE
Add case-insensitive configuration for keywords parsing

### ISSUE THREAD

**Issue by Pluralia** [langium/langium#315]
It would be great to add special syntax / parser's flag to define case-insensitive keywords. Currently it's possible to do only by a pretty exhausting pattern: use a regular expression of type `/[kK][eE][yY][wW][oO][rR][dD]/` for each keyword. The flag would allow to use usual `'keyword'` and say to parse it case-insensitive.

**Comment by dhuebner** [comment]
This is a nice first step  the direction to case-insensitive languages!
Most case-insensitive languages have also qualifier case-insensitive. That why I would like to suggest to have that flag in a higher level e.g. `LanguageMetaData` or `GrammarConfig`
