### ISSUE TITLE
Introduce runtime language configuration and UI settings

### ISSUE THREAD

**Issue by dhuebner** [langium/langium#344]
Some aspects of a language and its runtime behavior need to be configured by the user depending on the particular runtime environment and/or project setup.
One use-case is e.g. `DefaultIndexManager.skipFolder` where we need to exclude some folders from traversing during indexing.

The idea is to have a service that provides configurations for special property or a key (compared to Xtext PreferenceStoreAccess) at runtime.

When using in an IDE e.g. VSCode extension, we will need a corresponding implementation. In case of VS Code this can be user or workspace specific:
<img width="406" alt="Bildschirmfoto 2022-01-07 um 12 56 04" src="https://user-images.githubusercontent.com/454322/148540885-2a9dd33f-b13e-41fb-a552-f76d8cef67af.png">

For langium-vscode it would be nice to have a boilerplate code generated if possible.

**Comment by spoenemann** [comment]
> For langium-vscode it would be nice to have a boilerplate code generated if possible.

Configuration entries are declared in the package.json:
https://code.visualstudio.com/api/references/contribution-points#contributes.configuration

The language server can request configuration from the client:
https://microsoft.github.io/language-server-protocol/specification#workspace_configuration

This seems like there's not much to generate. Maybe we can add utility code using the configuration request for initializing the index.
