### ISSUE TITLE
Missing Rule from generated grammar

### ISSUE THREAD

**Issue by paulfrench** [langium/langium#378]
Langium version: 0.2.0

## Steps To Reproduce

1. Create default project using yo
2. Modify grammar as follows
```
Person:
    'person' name=ID default=Default;

Default:
  {IntConstant} value=INT |
  {StringConstant} value=STRING;
```
3. npm run langium:generate 
4. npm run build
`gives error` "src/language-server/generated/ast.ts:44:14 - error TS2304: Cannot find name 'Default'."

## Workaround

```
Person:
    'person' name=ID default=Default;

Default:
  IntConstant | StringConstant;

IntConstant:
  value=INT;

StringConstant:
  value=STRING;
```
## Expected
I believe both grammars above should produce the same output

**Comment by msujew** [comment]
@paulfrench Thanks for the bug report. We found similar issues in one of our own grammars. I think this will be fixed by #338.
