### ISSUE TITLE
Cross-references should be possible to do only on types

### ISSUE THREAD

**Issue by Pluralia** [langium/langium#382]
It's necessary to validate cross-references that they work only for types and not for rules.
Look at [the arithmetic example](https://github.com/langium/langium/blob/main/examples/arithmetics/src/language-server/arithmetics.langium#L35): cross-reference on `AbstractDefinition` in the `PrimaryExpression` is correct, because `AbstractDefinition` is a rule and also a type. However, we can replace the cross-reference on `AbstractDefinition` with an `Addition` without any errors, despite the `Addition` is only rule and not a type.

```
AbstractDefinition:
	Definition | DeclaredParameter;

Addition returns Expression:
	Multiplication ({BinaryExpression.left=current} operator=('+' | '-') right=Multiplication)*;

PrimaryExpression returns Expression:
	'(' Expression ')' |
	{NumberLiteral} value=NUMBER |
	{FunctionCall} func=[AbstractDefinition] ('(' args+=Expression (',' args+=Expression)* ')')?;
```

**Comment by spoenemann** [comment]
This affects all usages of types. For example, if you change the `DeclaredParameter` rule to
```
DeclaredParameter returns DP:
	name=ID;
```
its usage in the `AbstractDefinition` type should become invalid.
