### ISSUE TITLE
Problem when using a keyword also present as rule name

### ISSUE THREAD

**Issue by goto40** [langium/langium#387]
In Langium 0.2.0 I encountered a strange effect: when using a *rule name as keyword* (here: `UINT`) I get errors when entering a model with the corresponding  keyword in the editor.

Maybe I misunderstood something and this is intended behavior. In that case I would greatly appreciate a hint what I did wrong. Thank you for this open source project. 

The following grammar is used to reproduce the error:
```python
grammar HelloWorld
hidden(WS, SL_COMMENT, ML_COMMENT)
Model: (defs+=Def)+; 
Def: 'type' x=Type bits=UINT;
Type: MYUINT='UINT'|MYINT='INT';
//           ^^^^^^ (keyword)
terminal UINT returns number: /[0-9]+/;
//       ^^^^ (rule name)
terminal WS: /\s+/;
terminal ML_COMMENT: /\/\*[\s\S]*?\*\//;
terminal SL_COMMENT: /\/\/[^\n\r]*/;
```
Entering the following model yields the error below
```
type UINT 32
type INT 32
``` 
Error:
```
Expecting: one of these possible Token sequences:
  1. [UINT]
  2. [INT]
but found: 'UINT'
```

Note: change the rule name `UINT` to `INT` yields the error for the keyword `INT`. 

## Steps To Reproduce

1. create a hello world grammar and exchange the grammar with the grammar indicated above.
2. generate, build and start the editor as indicated in `langium-quickstart.md`.

Link to code example: 

 * https://github.com/goto40/langium/blob/main/packages/langium/test/misc/enum.test.ts#L46
 * Note: it may be simpler to copy-paste the code above (grammar+model) into the standard hello world example...

## The current behavior

An error is raised indicating that the `UINT` is expected, but  `'UINT'` is found.

## The expected behavior

No error

**Comment by msujew** [comment]
Hi @goto40, thanks for the report.

I think we already encountered this issue ourselves (https://github.com/langium/langium/issues/294) and also fixed it (https://github.com/langium/langium/pull/337). So I will close this already. This won't be an issue for 0.3 anymore :)
