### ISSUE TITLE
Autocompletion not working as expected on Arithmetics example

### ISSUE THREAD

**Issue by gfontorbe** [langium/langium#395]
Autocompletion does not return expected keywords in the Arithmetics example.

There is no suggestion for `module` in an empty file but suggestion for `def` works fine. Once the `module` keyword is in the file, there is no more suggestion for `def`. 

Langium version: 0.3

## Steps To Reproduce

1. Run Arithmetics Extension
2. Create new .calc file
3. Type 'm', no relevant suggestion
4. Type 'd', suggestion for `def``
5. Insert `module Test` then type 'd' on a new line, no relevant suggestion

## The current behavior
<img width="437" alt="Screenshot 2022-01-28 at 09 35 49" src="https://user-images.githubusercontent.com/44747557/151514658-8661378c-9ef3-449b-9586-2a205f1bc99d.png">
<img width="419" alt="Screenshot 2022-01-28 at 09 35 59" src="https://user-images.githubusercontent.com/44747557/151514676-5af91362-531d-4ab4-b1ba-85cd9b9bb401.png">
<img width="424" alt="Screenshot 2022-01-28 at 09 36 16" src="https://user-images.githubusercontent.com/44747557/151514690-10a28844-5ae0-4cc5-b9b1-c103a2ad30ed.png">

**Comment by msujew** [comment]
This issue has been addressed with https://github.com/langium/langium/pull/623.
