### ISSUE TITLE
Or ( || ) removes syntax-highlighting

### ISSUE THREAD

**Issue by MathiasSJacobsen** [langium/langium#399]
When using `"||"` in a rule, the syntax-highlighting disappears from on every lower (<=) level rules.

Langium version: 0.2.0

## Steps To Reproduce

1. Create a new grammar.
2. Define a rule that contains `"||" name=ID` .
3. Define a rule that contains `"let" name=ID`.
4. Then define an other rule that contains multiple of the first rule and second rule: 
```
OtherRule:  
"component" name=ID "{"
    ruleOnes+=RuleOne*
    ruleTwos+=RuleTwo*
"}"
```
5. Then run the plugin and try to make the grammar. Now the syntax-highlighting should only appear on the first line.

Link to code example: https://pastebin.com/CKcXgezy

## The current behavior
![Grammar with or ( || )](https://user-images.githubusercontent.com/47521785/152193294-2e8395c6-1fb3-4a2a-a810-84682f9683f2.png)
![Syntax-highlighting of grammar with or ( || )](https://user-images.githubusercontent.com/47521785/152193160-8e76d163-d3b7-41f3-8829-16d06f67c30b.png)

Her you can see that `let` is not purple.

## The expected behavior
![Grammar without or ( || ) ](https://user-images.githubusercontent.com/47521785/152192784-afd88e78-2bf4-4978-bbe6-0c1299d8f8e1.png)
![Syntax-highlighting of grammar without or ( || ) ](https://user-images.githubusercontent.com/47521785/152192900-70a53d1c-d533-42c7-87fb-03b6a61d8b99.png)

**Comment by msujew** [comment]
Hey, @MathiasSJacobsen thanks for the report.

Do you mind testing whether this is the same issue as described in here: https://github.com/langium/langium/discussions/349?

If it is fixed by adding the appropriate `\` in the `tmLanguage.json` file, then this issue has already been fixed with #293 and will release in 0.3 (this month).

**Comment by MathiasSJacobsen** [comment]
Hi, @msujew.

I don't think this is the same problem, or at least I can't seem to see that it is 😅.

This is the same line and there isn't missing any `\\`.
```json
"match": "(\\;|\\{|\\}|\\||)"
```
I guess the problem is that the second `|` in the `\\||`.

If you want to make a language able to say:
```kotlin
if (…… || ……) {
    …
}
```

**Comment by msujew** [comment]
@MathiasSJacobsen thanks for sharing the generated code, because there actually is an error in there. The `\\||` should actually be `\\|\\|`. Just `\\||` is a combination of an escaped `|` and a regex alternative. Can you try manually adding the second `\\`?

**Comment by MathiasSJacobsen** [comment]
I'm so sorry yes that worked. Didn't work late last night. Probably forgot to regenerate. Then I can't wait for the new release!
