### ISSUE TITLE
Consistency validation of inferred and declared types

### ISSUE THREAD

**Issue by pluralia** [langium/langium#415]
We should validate rules that are used a declared type: properties of such rules must match attributes of the declared type. An example below throws a validation error due to `MyRule` has a `ruleValue` property instead of a `typeValue` property.

```
interface MyType {
    typeValue: number;
}

MyRule returns MyType:
    ruleValue=NUMBER;
```

**Comment by spoenemann** [comment]
See https://github.com/langium/langium/pull/406#discussion_r810922786: we should also validate usages of `type`s for consistency. For example, this is not valid because `Foo` is not an AST node type.
```
type Foo = string;

Bar returns Foo: ...
```
