### ISSUE TITLE
Add type consistency validation for actions

### ISSUE THREAD

**Issue by pluralia** [langium/langium#447]
It's necessary to add validation for actions that use declared types. For example, interface `X` has a property `name`, but type `X` from action has a property `count` -- validation should forbid it.
```
interface X {
    name: string
}

MyXRule:
    {X} count=NUMBER;
```

**Comment by Lotes** [comment]
I had a chat with @msujew , this task is harder than I thought (it was looking a very innocent 'write a validator' task).
I will concentrate on a different task and release this issue for someone else.

**Comment by pluralia** [comment]
@Lotes, I take it. Thank you for your work!
