### ISSUE TITLE
Add validation of implicit `infers` usage

### ISSUE THREAD

**Issue by pluralia** [langium/langium#449]
We already validate incorrect explicit usage of `returns` and `infers` in #438 -- we should validate implicit usage too.

For example, a `Definition` rule can be defined without a return type, what implicitly means `Definition infers Definition`.
```
Definition:
    'def' name=ID ('(' args+=DeclaredParameter (',' args+=DeclaredParameter)* ')')? ':' expr=Expression ';';
```

If now interface `Definition` will be declared, we should validate, that the `Definition` rule has the return type `Definition` as `Definition returns Definition`.
```
Definition returns Definition: ...;

interface Definition {
    name: string
    expr: Expression
    args: DeclaredParameter[]
}
```
Depends on #440.

**Comment by dhuebner** [comment]
@pluralia 
As we will have Cross references soon, here I think we should change the linking implementation so that `returns Definition:` links to the `interface`. Doing so the validation will become obsolet.

**Comment by pluralia** [comment]
> Validation should warn the user to put the `returns Definition` to the Parser rule: `Definition: ... ;`

Yes, because otherwise `Definition: ... ;` will be recognized as `infers Definition`, what means that we have 2 definition types `Definition`: declared on from the interface `Definition` and inferred from the rule `Definition`.

**Comment by dhuebner** [comment]
We need to fix scoping anyways, currently in your example `returns Definition` will link to Parser rule `Definition` :)

**Comment by montymxb** [comment]
It seems this issue might be resolved. In the current version of langium (main) I get the following error for attempting to let `Definition` infer a type, when it has already been explicitly declared:

> The type 'Definition' is already explicitly declared and cannot be inferred.

<img width=550 alt="Image of Langium error: The type 'Definition' is already explicitly declared and cannot be inferred." src="https://user-images.githubusercontent.com/5070304/170660717-6eeac82a-2400-4f4f-b30d-c153e8d69747.png">

It seems like maybe a code action would be a great addition to cap this off, adding the `returns Definition` part that would be needed. Something that could be added to #442 ?

**Comment by msujew** [comment]
@montymxb I believed this behavior was already added by https://github.com/langium/langium/pull/461. But I agree having a quick fix for this would be great!
