### ISSUE TITLE
WorkspaceManager: loading in-memory models (fromString) yields error message in some situations 

### ISSUE THREAD

**Issue by goto40** [langium/langium#464]
Langium version: 0.3.0
Package name: langium

## Summary
(see https://github.com/langium/langium/discussions/391)

In Langium 0.3, in the WorkspaceManager: I wonder what is intended to be passed as URI to LangiumDocumentFactory.fromString when using an in-memory model (which has no corresponding file). Using a non-existing filename seems to work, but yields logs on the console in some situations:

The following happens when I move the cursor over a reference to the model built in memory (I used the URI URI.parse("built_in")).

```
[Error - 8:00:43 PM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: ENOENT: no such file or directory, open '/built_in'
  Code: -32603 
```

Probably I misunderstood how I should call the API?

## Steps To Reproduce

1. Create a custom `WorkspaceManager` extending the `DefaultWorkspaceManager`
2. There, in `loadAdditionalDocuments` load a built-in model from a string to be referenced from user models with the following snippet (note: the file "built_in" does not exist): 
```
const doc : LangiumDocument = this.factory.fromString(model_text, URI.parse("built_in"));
_collector(doc);
```
3. Reference data from the built-in-model in your user model (references are resolved correctly, no error).
4. Move with the cursor over the reference text
5. Then you get the "effect" in the vscode log ("Request textDocument/documentHighlight failed", see above)

Link to code example:

 * https://github.com/goto40/item-lang/blob/4a852104ae30f32e9bd8ed20b993b19a2aaeaed5/src/language-server/item-language-workspace.ts#L32 (if this example is too complicated, I can try to reproduce with a modified hello world example).
 * In this example you need to build the language and open the example with the generated plugin: https://github.com/goto40/item-lang/blob/4a852104ae30f32e9bd8ed20b993b19a2aaeaed5/examples/model/array_demo.item#L7
 * move over `built_in.uint32`

## The current behavior

You get a message `Request textDocument/documentHighlight failed`...

## The expected behavior

 * The ability to pass "no URL" to `fromString` or to document what to pass for in-memory model text snippets.
 * No such message: `Request textDocument/documentHighlight failed`...

**Comment by msujew** [comment]
Hey @goto40,

I believe that the `LangiumDocuments` service tries to resolve the in-memory file from the disk when getting the request, since it hasn't been added to the cache. Can you add a call to `LangiumDocuments#addDocument` and add `doc` this way?

Also `URI.parse("built_in")` creates a uri which actually tries to point to a file. Since the URI schema is missing, VSCode probably mistakenly expects that the URI points to a file. Something like `URI.parse("memory://built_in")` should be better.

**Comment by goto40** [comment]
Thank you @msujew ! Your suggestion (calling `this.langiumDocuments.addDocument(doc);`) solved the issue. Very good! I will add a hint in the discussion section.

**Comment by goto40** [comment]
> Thank you @msujew ! Your suggestion (calling `this.langiumDocuments.addDocument(doc);`) solved the issue. Very good! I will add a hint in the discussion section: #391.

Note: for langium 0.4.0 this is not necessary any more (if `addDocument` is called you get an error indicating the document is already loaded),
