### ISSUE TITLE
Guard expression breaks grammar

### ISSUE THREAD

**Issue by ruediste** [langium/langium#480]
I tried to use the guard expressions. This caused simple expressions not to be parsed anymore.

Langium version: 0.3.0

## Steps To Reproduce

Boilded down version of the Grammar: 
```
grammar OpenScad

entry Input: statements+=Expr<false> ';'; 

Expr<foo>: expr+=Multiplication<foo> ('+' expr+=Multiplication<foo>)*;
Multiplication<foo>: expr+=Primary<foo> ('*' expr+=Primary<foo>)*;

Primary<foo>: number=NUMBER;

hidden terminal WS: /\s+/;
terminal NUMBER returns number: /[0-9]+/;

hidden terminal ML_COMMENT: /\/\*[\s\S]*?\*\//;
hidden terminal SL_COMMENT: /\/\/[^\n\r]*/;

```
Input: 

```
1+2;
```

Output: 
```
There are validation errors:
line 1: Expecting keyword ';' but found `+`. [+]
line 1: Expecting end of file but found `+`. [+]
```

When I remove the guards the grammar works as expected.

## The current behavior
Adding the guards (if they are used or not does not matter, as far as I can tell) seems to mix something up in the area of cardinality handling.

## The expected behavior
Adding guards which are not used should not have an impact on the grammar.

**Comment by msujew** [comment]
@ruediste Thank you for the bug report! See https://github.com/langium/langium/pull/481 for a fix and an explanation on why this happened in the first place.

**Comment by ruediste** [comment]
Wow, quick fix. I trust it works now. Closing the issue.
