### ISSUE TITLE
Improve primitive types

### ISSUE THREAD

**Issue by pluralia** [langium/langium#482]
* Add `bigint` as a built-in type in grammar and make `date` with a capital letter
```
PrimitiveType returns string:
    'string' | 'number' | 'boolean' | 'Date' | 'bigint';
```
* Validate `bigint` as a return type of terminal rules

**Comment by pluralia** [comment]
Duplicates #199, that also can be considered as a follow-up where it's necessary to implement the default value converter for `bigint` and `date`.

**Comment by montymxb** [comment]
I can take this one :octocat:
