### ISSUE TITLE
Language server crash on 'name' Cross-Ref

### ISSUE THREAD

**Issue by montymxb** [langium/langium#483]
Assigning a cross reference to the `name` property in a Rule causes the language server to crash. 

This appears to be due to how cross references on the name property are handled internally. Possibly related to the way that cross references automatically utilize the `name` property to identify the reference.

Langium version: 0.3.0

## Steps To Reproduce

Take the [Hello World grammar](https://langium.org/docs/getting-started/#explaining-the-grammar) in the Getting Started section as an example:

1. Adjust the Greeting rule in `hello-world.langium` to use a property of `name` instead of `person` for the **Person** cross ref.
```
Greeting:
    'Hello' name=[Person:ID] '!';
```
2. Update the usages of this property in your project. In the hello-world case, this would be line **13** in **cli/generator.ts**.
3. Regen w/ Langium and rebuild the project
4. Launching the extension via F5 and viewing a file crashes the language server after a short delay with a msg like so:

```
Debugger listening on ws://127.0.0.1:6009/489f472b-13ac-4366-ba05-5058d0ab6ac5
For help, see: https://nodejs.org/en/docs/inspector
node:internal/child_process/serialization:127
    const string = JSONStringify(message) + '\n';
                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'elements' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property '$container' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:127:20)
    at process._send (node:internal/child_process:819:17)
    at process.send (node:internal/child_process:719:19)
    at IPCMessageWriter.write 
    ..... followed by a stack trace in the vscode-jsonrpc library, and then repeats about 3 times ....
```

I originally came across this on a separate example project, so it *appears* to be independent of the language implementation itself.

Ideally, this should should either not crash, or not be allowed if there's some limitation to rectifying the issue at this time.

**Comment by msujew** [comment]
Hi Ben :)

Interesting catch, the source of the error is our document symbol provider:

https://github.com/langium/langium/blob/115046b958a8d0bf34dbad8f89aa45fc3222a6a9/packages/langium/src/lsp/document-symbol-provider.ts#L44-L51

Encoding the non-string `name` property using JSON leads to the error. It looks like our `isNamed` function returns true if the `name` property exists. However, it should only return true, if the name property is also of type `string`:

https://github.com/langium/langium/blob/115046b958a8d0bf34dbad8f89aa45fc3222a6a9/packages/langium/src/references/naming.ts#L14-L16

**Comment by msujew** [comment]
This is also related to https://github.com/langium/langium/issues/468

**Comment by montymxb** [comment]
Thanks for the insight! Me and Mark (other Mark, new colleague) can work on this as a 'good first issue' for us to cut our teeth on.
