### ISSUE TITLE
Declared types validation for optional parameters and inheritance

### ISSUE THREAD

**Issue by gfontorbe** [langium/langium#488]
## Current behavior:
* In a declared type, if a parameter is declared as 'optional', a validation error is returned if the optional parameter is not present in a parser rule.
<img width="590" alt="Screenshot 2022-05-10 at 09 50 41" src="https://user-images.githubusercontent.com/44747557/167579866-1e355f24-2a04-4b05-92bf-17b31eca9138.png">

* declared types that extend other declared types do not take the inheritance into account
<img width="599" alt="Screenshot 2022-05-10 at 10 12 08" src="https://user-images.githubusercontent.com/44747557/167581390-993ff372-63c4-4674-9983-5d9ddafcab4d.png">
<img width="371" alt="Screenshot 2022-05-10 at 10 12 18" src="https://user-images.githubusercontent.com/44747557/167581422-4bb18769-7ee9-441a-928e-405bb9e32eca.png">

## Expected behavior:
* No error should be returned if an optional parameter is not present in the parser rule.

* Inherited interface should also validate parent types

## Steps to reproduce
Optional parameters:
```
interface MyType {
    name: string
    count?: number
}

X returns MyType : name=ID;
```

Inheritance:
```
interface Foo {
    name: string
}

interface Event extends Foo {}

Event returns Event:
    name=ID;
```

**Comment by spoenemann** [comment]
About the inheritance: In general, we should compare types structurally (like TypeScript does), not based on interface inheritance.

**Comment by montymxb** [comment]
@gfontorbe would it be reasonable to break out the inheritance case into a separate issue? I have a fix for the original case, but not one for inheritance.
