### ISSUE TITLE
Langium CLI generates invalid code when chevrotainParserConfig is specified for a specific language

### ISSUE THREAD

**Issue by theogiraudet** [langium/langium#513]
When overwritting the chevrotainParserConfig property in the `langium-config.json`, Langium CLI generates an invalid `generate/module.ts` by adding the `<LanguageId>ParserConfig: IParserConfig` without importing IParserConfig.

![image](https://user-images.githubusercontent.com/28688370/170291348-54266cca-6c57-4618-bbd4-4eb8d63eea59.png)

## Error source
In [module-generator.ts](https://github.com/langium/langium/blob/main/packages/langium-cli/src/generator/module-generator.ts), the `IParserConfig` interface is imported only if `chevrotainParserConfig` is defined in the global configuration:
https://github.com/langium/langium/blob/82572206f172a91f6a09f3e69558cb96bb4392e5/packages/langium-cli/src/generator/module-generator.ts#L13
https://github.com/langium/langium/blob/82572206f172a91f6a09f3e69558cb96bb4392e5/packages/langium-cli/src/generator/module-generator.ts#L23
But never when it's defined in a specific language (and no in the global scope):
https://github.com/langium/langium/blob/82572206f172a91f6a09f3e69558cb96bb4392e5/packages/langium-cli/src/generator/module-generator.ts#L58-L59

Langium version: 0.3

## Steps To Reproduce

1. Generate the Hello World project
2. Modify the `langium-config.json` by adding `"chevrotainParserConfig": {"maxLookahead": 4},` in the language configuration.
Example:
```json
{
    "projectName": "SysmlV2",
    "languages": [{
        "chevrotainParserConfig": {"maxLookahead": 4},
        "id": "sysml-v2",
        "grammar": "src/language-server/sysml-v2.langium",
        "fileExtensions": [".sysml2"],
        "textMate": {
            "out": "syntaxes/sysml-v2.tmLanguage.json"
        }
    }],
    "out": "src/language-server/generated"
}
```
3. Run `npm run langium:generate` then `npm run build`

Minimal Langium project:
https://github.com/theogiraudet/Minimal-Langium-CLI-Error.git

## The current behavior
The absent of the import and a thrown exception.

## The expected behavior
The presence of the import.

**Comment by Lotes** [comment]
This one was already fixed by @pluralia with PR #455 .
