### ISSUE TITLE
Langium grammar can declare AST elements with conflicting names

### ISSUE THREAD

**Issue by RGHenderson** [langium/langium#529]
Langium version: 0.3.0
Package name: langium

## Steps To Reproduce

1. Create a minimal grammar containing an entry rule, and reference to a rule of name 'Error'
2. Run langium generator3. 
3. Run build
4. See error something like:
```
src/language-server/generated/ast.ts:59:27 - error TS2351: This expression is not constructable.
  Type 'String' has no construct signatures.

59                 throw new Error(`${referenceId} is not a valid reference id.`);
```
Which makes sense given the content of the generated ast.ts:
```
export interface Error extends AstNode 
...
export const Error = 'Error';
```

Minimal grammar which causes error:
```
grammar ErrorExample

entry ErrorExample:
    errors+=Error;

Error:
    'error' name=ID;

terminal ID: /[_a-zA-Z][\w_]*/;
```

## The current behavior
Langium allows the definition of conflicting AST element names, causing the above build error. 

## The expected behavior
Either the generated AST will be more smart, **OR** langium grammars are validated against reserved rule names.

**Comment by msujew** [comment]
Thanks for the report @RGHenderson! We should probably add reserved names for built-in JavaScript types. The only other option would be to rename them automatically, which would be quite unintuitive for users.
