### ISSUE TITLE
Provide go to definition for grammar imports

### ISSUE THREAD

**Issue by dhuebner** [langium/langium#584]
It would be nice to jump to the imported grammar using `F12` or `CMD+Click` in `"myothergrammar"` , see blow:

```js
import "myothergrammar"
```

**Comment by dhuebner** [comment]
Looks like it is not easily possible to extend the current default implementation, because the current API assumes GoTo definition will only work with Langium to Langium links, which is not always the case.   

@spoenemann 
I would like to propose an additional template method that has the `source ` LeafNode as input and returns `MaybePromise<LocationLink[] | undefined>` or allow existing `findLink` method to return `GoToLink` or `LocationLink `
https://github.com/langium/langium/commit/dff52c0d9eedad089ad51ce88dbcaf2b5ae29350#diff-836d28b4051237dff5a5fcdaa997cb9d48ec6e7ee2e79c563242d106c6f05ca8R19

**Comment by gfontorbe** [comment]
@dhuebner If/when #575 lands, `grammar-goto.ts` would be deleted (since what it was doing before is now the responsibility of the `References` service).

I would assume that the PR would not solve your issue, but it would be good to check how compatible they are

**Comment by dhuebner** [comment]
@gfontorbe 
Thanks I will take a look. Where is the hook/API for https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition now?

**Comment by gfontorbe** [comment]
@dhuebner The default GoToResolver is in `packages > langium > src > lsp > goto.ts`
