### ISSUE TITLE
Validate cross references to global but not imported types

### ISSUE THREAD

**Issue by dhuebner** [langium/langium#585]
Currently any objects from the global scope can be referenced in the Grammar.
This will fail in CLI, as in CLI we index or lookup only Langium documents that are directly or transitively imported in the root 
Grammar.

In some places we are already validating references to a not imported object, like e.g. for rules, but interfaces and types can still be used without explicitly importing them.

Example:
grammar.langium
```js
grammar Test_file_ref

// import "types" <-- no import

entry Root returns IRoot: // IRoot can still be used. Should be marked as error
    name=ID;
```

types.langium
```js
interface IRoot {

}
```

We need a validation for that.
Alternatively we can decide to shrink the default Langium scope, but have an extended scoping implementation for the content assist.

**Comment by msujew** [comment]
@hpopov Thanks, you're right, it's been fixed by https://github.com/langium/langium/pull/763 👍
