### ISSUE TITLE
Support `textDocument.signatureHelp` LSP request

### ISSUE THREAD

**Issue by msujew** [langium/langium#594]
The service (something like `SignatureHelpService`) should be accompanied with an `AbstractSignatureHelpProvider` that gives us the current AST element at the cursor position.

**Comment by gfontorbe** [comment]
@msujew I never tried to implement a new service from scratch but would like to have a go at it if possible. I can start in 2 weeks when I am back from vacation

**Comment by gfontorbe** [comment]
#612
