### ISSUE TITLE
langium:generate fails with imported grammars

### ISSUE THREAD

**Issue by goto40** [langium/langium#671]
When importing a file (`import './grammar'`) 'langium:generate' produces an error: `TypeError: Cannot read properties of undefined (reading '$container')`.

Langium version: 8c5d43d26a2afd9dadacff02328ff619d74df30b
Package name: langium

## Steps To Reproduce

1. checkout langium @ 8c5d43d26a2afd9dadacff02328ff619d74df30b
2. `npm ci`
3. add file `dummy.langium` with `terminal Dummy: '*dummy';` inside at `examples/domainmodel/src/language-server`.
4. add `import './dummy'` in `domain-model.langium` 
5. `npm run langium:generate -w example/domainmodel`

## The current behavior

```
npm run langium:generate -w examples/domainmodel/

> langium-domainmodel-dsl@0.4.0 langium:generate
> langium generate

Reading config from langium-config.json
src/language-server/domain-model.langium:34:10 - This rule is declared but never referenced.
src/language-server/domain-model.langium:35:10 - This rule is declared but never referenced.
TypeError: Cannot read properties of undefined (reading '$container')
npm ERR! Lifecycle script `langium:generate` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: langium-domainmodel-dsl@0.4.0 
npm ERR!   at location: /home/pierre/internet/langium/examples/domainmodel 
```

## The expected behavior

no such error.

**Comment by goto40** [comment]
I also debugged a little bit but I do not have enough knowledge/experience to find my way at the current state of my experiments...

It seems to happen in the constructor of `LangiumParser` `langium-parser.ts`, while assigning `this.linker = services.references.Linker;`.

**Comment by msujew** [comment]
I can confirm the issue. This seems to be a side effect of https://github.com/langium/langium/pull/546, which is why this issue doesn't appear in version 0.4. However the fix is luckily very simple, see https://github.com/langium/langium/pull/672.

Thanks for catching this 👍
