### ISSUE TITLE
langium.org down

### ISSUE THREAD

**Issue by kaby76** [langium/langium#713]
Link is in the [readme](https://github.com/langium/langium/blob/7305814026c17348df65e5d13cb9daaba8fd2437/README.md?plain=1#L37) https://langium.org/

I get `Error - Request ID: 01GEN0RC0BJ3575HZFAPDKCXG8`

**Comment by pluralia** [comment]
Could you please try again? It works for me.

**Comment by kaby76** [comment]
Ok, now it's back up.
