### ISSUE TITLE
Strange effect when using a terminal name in an "enum"

### ISSUE THREAD

**Issue by goto40** [langium/langium#719]
Langium version: 0.5.0
Package name: langium

## Steps To Reproduce

1. generate hello-world project
2. change grammar (only changed part is shown):
  ```
  Person:
      'person' name=ID lastname=STRING 'with' info=INFO;
  INFO returns string: 'ABC'|'STRING'|'INT';
  ```

## The current behavior

Now a model with `STRING` as value for `info` cannot be entered:
![image](https://user-images.githubusercontent.com/16887130/195445127-f85bde67-7524-4972-8157-bf3b9231be41.png)

if `lastname=STRING` is ommited from the model (leading to an usued rule `STRING`) the problem does not occur.

I am not sure if this related to https://github.com/langium/langium/issues/561 or if I misunderstood something...

## The expected behavior

No such restriction

**Comment by goto40** [comment]
For the moment I use a workaround to name my rule differently (e.g. `String` instead of `STRING`)

**Comment by msujew** [comment]
This is likely related to https://github.com/langium/langium/issues/294. I would've recommended your workaround for now as well. I'll dig into why this happens in the first place sometime soon.

**Comment by msujew** [comment]
Related to https://github.com/langium/langium/issues/810.
