### ISSUE TITLE
Monarch Grammar Generation does not Escape / Symbol

### ISSUE THREAD

**Issue by montymxb** [langium/langium#740]
For Langium 0.5.0, the [Monarch grammar generator does not properly escape forward slash `/` symbols as part of the generated output](https://github.com/langium/langium/blob/main/packages/langium-cli/src/generator/highlighting/monarch-generator.ts#L240). The result is a broken monarch grammar for any languages that use the `/` symbol. This comes up in the division case, as a simple example.

Initially I figured changing the `escapeRegExp` function to also escape forward slashes would work, but this breaks other tests in Langium that depend on *not* escaping the forward slash in some cases. Those cases could be changed, but to keep things working, it might be nice to simply add an extra case for escaping this symbol on its own in the Monarch generator for now.

A good test to make sure this is working is to generate a Monarch grammar for the [MiniLogo language](https://github.com/langium/langium-minilogo), which has this problem with the generated Monarch file.

**Comment by pluralia** [comment]
The issue is still active for the Langium 1.1.0: `generateMonarch` doesn't add an escape symbol before `/`. You can see the problem in [the arithmetic example](https://github.com/langium/langium/blob/main/examples/arithmetics/syntaxes/arithmetics.monarch.ts#LL9C39-L9C39).
