### ISSUE TITLE
Unimported grammar file affects other files with the same name rules

### ISSUE THREAD

**Issue by luan-xiaokun** [langium/langium#746]
Some grammar files in the workspace are never imported in other files, and they may have parse rules that have the same names with other rules in the irrelevant files (e.g. a debugging grammar file). In very rare cases, editing these unimported files raises error `Referenced rule "X" is not imported`.

An example is shown as follows.

`debug.langium` is the main file, it imports `foo.langium` file which contains interface declaration. `bar.langium` is an irrelevant grammar file that is not imported in any of these two files, and also it has some rules that have the same names as those in the main file. Here is what happens in the gif:
1. When the editor is opened, everything is fine.
2. When the unimported file is edited (but not saved), the main file raises error.
3. The error disappears after undoing the change or saving the change.
4. After that, editing the unimported file has no effect on the main file.

![Peek 2022-10-31](https://user-images.githubusercontent.com/43921595/199027007-04c5f9c3-db5c-426a-93d0-178828c30707.gif)

A few more facts:

1. The error disappears after merging `debug.langium` and `foo.langium`.
2. Removing the entry rule in `bar.langium` does not help.
3. The error also occurs when the file is moved, except when the editor is first started.

Code for this example:
```
// file debug.langium
grammar Debug

import './foo'

entry Model:
    (items+=AB)*;

A returns A:
    'AB' a=ID;

AB returns AB:
    A ({B} b+=ID)*;

hidden terminal WS: /\s+/;
terminal ID: /[_a-zA-Z][\w_]*/;
```
```
// file foo.langium
interface A {
    a: string;
}
interface B {
    b: string[];
}

type AB = A | B;
```
```
// file bar.langium
grammar Debug

entry Model:
    (items+=AB)*;

A infers A:
    'A' a=ID;

B infers B:
    'B' b=ID;

AB:
    A ({infer B} b+=ID)*;

hidden terminal WS: /\s+/;
terminal ID: /[_a-zA-Z][\w_]*/;
```

**Comment by dhuebner** [comment]
We should start honor import declarations and stop using the global scope

**Comment by spoenemann** [comment]
Yes, that could help to avoid such problems. If we want to auto-import declarations, we could still do that by customizing the completion provider.
