### ISSUE TITLE
Declared types as container types

### ISSUE THREAD

**Issue by pluralia** [langium/langium#750]
Container types are computed based on inferred types only. We should add declared types as container types too.

**Comment by Lotes** [comment]
Forgive my missing knowledge, what do you mean with containers? How is it done for inferred types and how should it look for declared types?

**Comment by pluralia** [comment]
> what do you mean with containers?

Each `AstNode` has a `$container` property. Its type lists all possible `AstNode`s that can contain that `AstNode`. For example, container type of `NumberLiteral` in [the arithmetic example](https://github.com/langium/langium/blob/main/examples/arithmetics/src/language-server/generated/ast.ts#L106) is `BinaryExpression | Definition | Evaluation | FunctionCall` what means, a parent object of a `NumberLiteral` object, can be `BinaryExpression` or `Definition`, etc.

> How is it done for inferred types

This question has a long answer. I leave a link to [the source code](https://github.com/langium/langium/blob/main/packages/langium/src/grammar/type-system/inferred-types.ts#L484-L532) and to [the issues](https://github.com/langium/langium/issues/150) about problems with current calculation as it has some explanation. Let me know if you still have questions.

> how should it look for declared types?

The same like for inferred types. Basically, to close this issue, it's necessary just add declared types in calculation of container types that it would happen not only on inferred ones.

**Comment by Lotes** [comment]
Thank you. I am convinced that the task becomes easier when we would model the rules and alternatives as types with properties inside of a type-property-graph.
The arithmetic example might be a good starter to talk about the contents of the nodes and edges. I can prepare a visualization next week.

**Comment by Lotes** [comment]
![Arithmetic](https://user-images.githubusercontent.com/1525964/200125914-466a8c66-180e-4fa3-9ba9-f692cdb68acb.png)
Done with SimpleMind :3

**Comment by Lotes** [comment]
![Contains](https://user-images.githubusercontent.com/1525964/200126670-553a43ab-dd2f-4696-9860-534f3b9de9e7.png)
Here are the containment relations minus primitive types.

**Comment by Lotes** [comment]
```
foreach t: type:
  find: (container: type)—[has-property]->(:property)-[has-type]->(t:type)
  containers[t].push(container)
  find: (container: type)—[has-property]->(:property)-[has-type]->(:type)<—[extends*]-(t: type)
  containers[t].push(container)
```
Easy! :D
