### ISSUE TITLE
Generate an AST visitor in addition to the AST

### ISSUE THREAD

**Issue by msujew** [langium/langium#81]
Often times I want to just go through some objects of the AST (e.g. for validation) without streaming the whole AST tree. For this, we should think about generating an AST visitor which we can use to override certain visitor methods.

**Comment by brucou** [comment]
@msujew I am chiming in. Apologies in advance if I misunderstood you but I more than often solved these issues with simple helpers.

So this:

```js
streamAllContents(rule).forEach(e => {
    if (isRuleCall(e.node) && isParserRule(e.node.rule.ref)) {
        accept('error', 'Primitive rules can only call other primitive rules or terminal rules', { node: e.node });
    }
    if (isAction(e.node)) {
        accept('error', 'Primitive rules cannot contain actions.', { node: e.node });
    }
    if (isAssignment(e.node)) {
        accept('error', 'Primitive rules cannot contain assignments.', { node: e.node });
    }
});
```

can be written as:

```js
streamAllContents(rule).forEach(e =>patternMatch( [
    ['ParserRule', parserRule => ...],
    ['Action', action => ...],
    ...
]));
```

You have to write the patterMatch function of course. But you only have to write it once, it is not that hard to write, and you can use the functional library Ramda to do so if you are proficient in functional programming.

Bottom-line is I generally support keeping the surface API of a library low, and pusing to userland what can be done there. So I would tend to agree with @danieldietrich here.

**Comment by msujew** [comment]
Thank you @brucou for your input. I guess you are right, using a pattern matching method in there makes more sense than going through the trouble of building a dedicated visitor. I'll close this issue.
