### ISSUE TITLE
Missing TokenType when converting to `TokenTypeDictionary`

### ISSUE THREAD

**Issue by luan-xiaokun** [langium/langium#810]
Originally brought up [here](https://github.com/langium/langium/issues/561#issuecomment-1330869348)

> I have a probably similar problem: When creating the hello-world-language (langium 0.5.0) and changing the grammar from 'person' name=ID to 'ID' name=ID I get a problem:
> 
> Person:
>     'ID' name=ID;
> 
> with the model
> 
> ID Pierre
> Hello Pierre!
> 
> --> Error "Expecting token of type 'EOF' but found ID.hello-world(parsing-error)".
> 
> Renaming the rule ID to Id fixes the issue...

This error occurs after v0.5.0. 

`toTokenTypeDictionary` (in parser/lexer.ts) seems to be the cause of this issue. It converts a tokentype vocabulary to a dictionary. If there are two tokens both having the name 'ID', where one of them is the keyword with a pattern 'ID', and the other is the terminal rule with the pattern '[a-zA-Z_]\w*', then the current `toTokenTypeDictionary` will only keep the later one because of the following line of code.
```ts
tokens.forEach(token => res[token.name] = token);
```

**Comment by msujew** [comment]
We should resolve this by either giving terminal token type a special, unique token name (something similar to what we're already doing for [parser rules](https://github.com/langium/langium/blob/f6c5e546e015b7b3031c00ede1fc378f0fd30c52/packages/langium/src/parser/langium-parser.ts#L67-L68), or alternatively validate that no keyword shares its content with any terminal.
