### ISSUE TITLE
Define an API evolution concept

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#842]
Inspiration: https://github.com/eclipse-theia/theia/blob/master/doc/api-management.md

**Comment by Lotes** [comment]
Uh nice! Are there tools to determine whether the state is compatible to the last (semantic) version?

**Comment by spoenemann** [comment]
Code reviews 😁

**Comment by dhuebner** [comment]
I only found  this old and inactive JS package/repo https://www.npmjs.com/package/cracks . 
Static analysis libraries like ts-morph are available, why are there any CLI tools or vs-code extensions for that? That is really strange.

**Comment by dhuebner** [comment]
Maybe we can add some tests like described here: https://lostintime.dev/2021/01/02/typescript-api-breaking-changes.html
But seems to be a lot of work for a huge codebase like ours

**Comment by Lotes** [comment]
I like the last idea, since we might want to respect annotations like STABLE, EXPERIMENTAL, DEPRECATED.
