### ISSUE TITLE
Consider existing declared interfaces when infering types

### ISSUE THREAD

**Issue by msujew** [langium/langium#844]
In some cases, users might want to have an empty interface instead of a union type. In this case, the user should be able to declare a new empty interface which won't be overriden by an inferred union type. Currently a validation prevents such an issue.

**Comment by dhuebner** [comment]
@msujew 
I was about to report the same.
My additional point is that it doesn't necessarily have to be an empty interface.

Example:

```ts
interface AbstractElement {
    name: string
}

AbstractElement returns AbstractElement:
    PackageDeclaration | DataType;

PackageDeclaration:
    'package' name=QualifiedName '{'
        (elements+=AbstractElement)*
    '}';

DataType:
    'datatype' name=ID;

```
