### ISSUE TITLE
langium extract-types acts unexpectedly for multi-languages

### ISSUE THREAD

**Issue by l-ehlers** [langium/langium#864]
When using `langium extract-types` (introduced in #754) on a grammar that is spread across different files, the type extraction does not work correctly. In fact, if no explicit types have been declared for the specified grammar file, only the lastly imported grammar file is taken into account by the langium-cli tool.

**Note: I know the tool is not published/documented yet, and I have no need for a fix of the tool, but I wanted to share my findings with you anyway**

Probably, the described behavior is caused by this line: https://github.com/langium/langium/blob/main/packages/langium-cli/src/generate.ts#L305

Langium version: v1.0.1
Package name: langium-cli

## Steps To Reproduce

1. Create the multi-language depicted below
2. Run `langium extract-types A.langium`
3. Swap `A`'s imports to `B` and `C`
4. Run `langium extract-types A.langium` again

### A.langium
```
grammar A

import "B"
import "C"

entry A: b=B c=C;
```

### B.langium
```
import "terminals"

B: valB=ID;
```

### C.langium
```
import "terminals"

C: valC=ID;
```

### terminals.langium
```
terminal ID: /[_a-zA-Z][\w_]*/;
```

### First generation
```
interface C {
    valC: string
}
```

### Second generation (with swapped imports in A)
```
interface B {
    valB: string
}
```

## The expected behavior

Either a correct typing file such as 
```
interface A {
    b: B
    c: C
}

interface B {
    valB: string
}

interface C {
    valC: string
}
```

or one typing file for each grammar file (maybe configurable)

or just an error "multi-languages are not supported by `extract-types`"

(Interestingly, the type generation seems to work just fine for multi-languages with types that have already been declared)

**Comment by dhuebner** [comment]
Fixed on master
