### ISSUE TITLE
Fragments that assign to arrays only assign the last parsed element

### ISSUE THREAD

**Issue by daumantas-kavolis-sensmetry** [langium/langium#896]
Langium version: 1.0.1
Package name: langium

Fragments that assign to an array only assign the last parsed element when used with `+` or `*` cardinalities. This is a serious bug that prevents using fragment composition in more complex grammars for parsing declarations and bodies without resorting to copy-pasting .

## Steps To Reproduce

1. Replace

```langium
entry Model:
    (persons+=Person | greetings+=Greeting)*;
```

with

```langium
entry Model:
    ModelItem*;

fragment ModelItem:
    persons+=Person | greetings+=Greeting;
```

Link to code example:

[Link to playground](https://langium.org/playground?grammar=OYJwhgthYgBAEgUwDbIPYHU0mQEwFD6IB2ALiAJ6wCyauKAXPrCzXSgJKmIQBUA3IQBm4YBBKk29ZFx5NWsAA6IQAZzTFVAagC8ABRXrisAD6xQiRKQCWxYNp0BxEJZt3B%2BA2o3zWAcmVvYj9YYkhEHQ4AEQ9nV1tgXxY-JFQ0EMCjHQBtLyMGaIBdWD8AQj8PAAtrXHpjbhAIWzBkWAwAZQZYAHoAHW1uwQamsNboru7sgH0wAFoALwBBWYAtQuzegHcpwt5Bwmraklhh5tbqABkpgGEAeWpqAFEAOQAVCd6%2B3g3VXvbdgD8vV4n32hzqJxUIxasHaVzuDxe7x6n0%2B2QAer1iL0QLt9kA&content=A4UwTgzg9gdgBAKSgCxgKFJWiCGMRpoASIANqVIijAITFkW751A)

## The current behavior

```js
{
  $type: "Model",
  greetings: [
    {
      $type: "Greeting",
      person: Reference("/persons@0"),
    },
  ],
  persons: [
    {
      $type: "Person",
      name: "Jane",
    },
  ],
}
```

## The expected behavior

```js
{
  $type: "Model",
  persons: [
    {
      $type: "Person",
      name: "John",
    },
    {
      $type: "Person",
      name: "Jane",
    },
  ],
  greetings: [
    {
      $type: "Greeting",
      person: Reference("/persons@0"),
    },
    {
      $type: "Greeting",
      person: Reference("/persons@1"),
    },
  ],
}
```

**Comment by msujew** [comment]
Hey @daumantas-kavolis-sensmetry, thanks for the report. I've created #898 to fix this issue.
