### ISSUE TITLE
Support transitive imports

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [langium/langium#924]
I have several XText grammars with dependencies as follows:
```
grammar com.epistimis.face.Face with com.epistimis.uddl.Uddl
grammar com.epistimis.uddl.Uddl with org.eclipse.xtext.common.Terminals
```
I have used XText2Langium, v. 0.4.0 to generate the equivalent Langium grammars.

When I generate from the Uddl grammar, I get the following in `Uddl.langium`:
```
grammar Uddl
import 'Terminals'
```

When I generate from the Face grammar, I get the following in `Face.langium`:
```
grammar Face
import 'Uddl'
```

When I open the `Face.langium` grammar, I get a lot of errors `Could not resolve reference to AbstractRule rule named 'ID'`

I can resolve this by adding `Import Terminals` at the top of the `Face.langium` file. But I shouldn't have to. Since `Uddl.langium` imports `'Terminals'`, importing `'Uddl'` should transitively import everything it imports. This is how C++ includes work. 

If you decide that Langium imports should not work like C++ includes, then this is a bug for XText2Langium - it should recurse into all grammar dependencies and import those dependencies.

**Comment by spoenemann** [comment]
I propose not to import transitively and to fix this in xtext2langium instead (CC @dhuebner). I would lean to the import mechanism of TypeScript rather than C++.

**Comment by msujew** [comment]
I agree with @dhuebner. Since the `langium-cli` already correctly works with transitive imports, I believe we should adjust the scope accordingly.
