### ISSUE TITLE
[arithmetics] Missing essential validations

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#933]
We should add essential validations to the arithmetics example (and maybe other examples as well):
 - Duplicate definition name
 - Duplicate parameter name
 - Argument list not matching the number of definition parameters

**Comment by emilkrebs** [comment]
Interesting, I will take care of this.

**Comment by emilkrebs** [comment]
Fixed it

**Comment by spoenemann** [comment]
AFAICT the PR #968 addresses "Duplicate definition name", but not the other two things I mentioned.

**Comment by spoenemann** [comment]
Fixed with #968 and #1013.
