### ISSUE TITLE
Declared union type leads to nonsense code in ast.ts

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#957]
I noticed this while looking at #941: When you add a union type like `type StateType = 'normal' | 'final'`, you get these declarations in ast.ts:

```typescript
export type StateType = 'final' | 'normal';

export const StateType = 'StateType';

export function isStateType(item: unknown): item is StateType {
    return reflection.isInstance(item, StateType);
}
```

The `const` and the `function` don't make sense because this is not an AST node. I propose to suppress generating those when the type does not represent an AST node.

**Comment by msujew** [comment]
Related to https://github.com/langium/langium/issues/941
