### ISSUE TITLE
Generated CLI does not have execution permission and has CRLF issue

### ISSUE THREAD

**Issue by luan-xiaokun** [langium/langium#989]
Langium version: 1.1.0
Package name: langium

The generated CLI does not have execution permission, and executing it on Linux platform gives an error `/usr/bin/env: "node\r": No such file or directory`. It seems that this is because the first line ends with a `\r\n`.

**Comment by msujew** [comment]
It's very likely due to me performing the latest release on my windows machine. I'll update the yeoman generator to respect the OS line delimiter.

**Comment by msujew** [comment]
This has been resolved by https://github.com/langium/langium/pull/1005.
